LABELS = {
    # ChangeStatus
    "DRAFT": "草稿",
    "SUBMITTED": "待核准",
    "APPROVED": "已核准",
    "IN_PROGRESS": "執行中",
    "PAUSED": "暫停",
    "EXECUTED": "待回填紀錄",
    "CLOSED": "已結案",
    "CANCELLED": "已取消",
    # StepStatus / ChangeResult
    "PENDING": "待執行",
    "DONE": "完成",
    "FAILED": "失敗",
    "SKIPPED": "省略",
    "ROLLED_BACK": "已回復",
    "SUCCESS": "成功",
    "PARTIAL": "部分成功",
    # SkipPolicy
    "REQUIRED": "必要",
    "OPTIONAL": "可省略",
    "CONDITIONAL": "條件式",
    # Risk
    "LOW": "低",
    "MEDIUM": "中",
    "HIGH": "高",
    # ModuleStatus
    "CANDIDATE": "候選",
    "STANDARD": "標準",
    "DEPRECATED": "停用",
    # ReviewDecision
    "KEEP_ONE_TIME": "保留為一次性調整",
    "PROMOTE": "晉升為標準模組",
    "MERGE_PARENT": "併入母模組新版本",
    # DeviceType
    "NETWORK": "網路設備",
    "WINDOWS": "Windows",
    "LINUX": "Linux",
    "OTHER": "其他",
    # Role
    "REQUESTER": "申請人",
    "APPROVER": "核准者",
    "OPERATOR": "執行者",
    "MODULE_EDITOR": "模組編輯",
    "MODULE_APPROVER": "模組核准",
    "AUDITOR": "稽核",
    "ADMIN": "系統管理",
    # transitions
    "submit": "送審",
    "approve": "核准",
    "reject": "退回",
    "start": "開始執行",
    "pause": "暫停",
    "resume": "繼續",
    "finish": "執行完畢",
    "cancel": "取消變更",
}
